tms/tms/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todos.urls')),
    # path('api/token/', TokenObtainPairView.as_view(), name = 'token_obtain_pair'),
    # path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh_pair'),
    # path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

tms/todos/urls.py
from . import views
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

#_______________________#
from rest_framework import routers
from .views import TodoViewSet

router = routers.DefaultRouter()
router.register(r'todo', TodoViewSet)
#________________#

urlpatterns = [
    path('', views.todos, name="todos"),
    path('todo/<int:id>/', views.TodoDetail.as_view(), name="one_todo"),
    path('review/<int:id>/', views.AddComment.as_view(), name="add_comment"),
    path('<int:id>/add_likes/', views.AddLike.as_view(), name='add_likes'),
    path('<int:id>/del_likes/', views.DelLike.as_view(), name='del_likes'),
    path('todo/<int:pk>/update', views.TodoUpdateView.as_view(), name="todo_update"),
    path('todo/<int:pk>/delete', views.TodoDeleteView.as_view(), name="todo_delete"),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login, name='login'),
    path('create/', views.create, name="create"),
    path('api/v2/', include(router.urls)),                              #http://127.0.0.1:8000/api/v2/todo/

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh_pair'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

tms/todos/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    '''задания
    поля: название задачи, описание, дата создания, автор, выполнена/не выполнена'''
    title = models.CharField(max_length=120, default='')
    description = models.TextField(default='')
    created_date = models.DateField(default=date.today)
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/todo/{self.id}'

    class Meta:
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'


class Comment(models.Model):
    '''комментарий под записью'''
    email_address = models.EmailField(default='')
    name = models.CharField(max_length=50, verbose_name='Имя пользователя')
    comment_text = models.TextField(max_length=2000, verbose_name='Текст комментария')
    comment = models.ForeignKey(Todo, on_delete=models.CASCADE, verbose_name='Задача')

    def __str__(self):
        return self.name, self.comment

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural  = 'Комментарии'


class Likes(models.Model):
    '''Лайки'''
    ip = models.CharField('IP-адрес', max_length=100)
    post = models.ForeignKey(Todo, verbose_name='Задание', on_delete=models.CASCADE)

tms/todos/forms.py
from django import forms
from .models import *
from django.forms import ModelForm, TextInput, DateTimeInput, NullBooleanSelect, Textarea, EmailInput


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ['title', 'description', 'created_date', 'author', 'completed']

        widgets = {
            "title": TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Название задачи'
            }),
            'description': Textarea(attrs={
                'class': "form-control",
                'placeholder': 'Содержание задачи'
            }),
            'created_date': DateTimeInput(attrs={
                'class': "form-control",
                'placeholder': 'Дата публикации'
            }),
            'author': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Автор'
            }),
            'completed': NullBooleanSelect(attrs={
                'class': "form-control",
                'placeholder': 'Выполнено'
            })
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email_address', 'comment_text')

tms/todos/views.py
from django_filters.rest_framework import DjangoFilterBackend

from django.shortcuts import render, redirect
from .forms import *
from django.views.generic import DetailView, UpdateView, DeleteView
from django.views.generic.base import View
from .forms import CommentForm
from rest_framework import generics, viewsets, permissions, filters
from .serializers import TodoSerializer
from .permissions import IsAdminReadOnly, IsOwnerOrReadOnly


def todos(request):
    todos = Todo.objects.all()
    context = {
        'todos': todos,
        'title': 'Главная страница'}
    return render(request, 'todos.html', context=context)


class TodoDetail(View):
    '''отдельная запись'''
    def get(self, request, id):
        one_todo = Todo.objects.get(id=id)
        return render(request, 'todo.html', {'one_todo': one_todo, 'title': one_todo.title})


class AddComment(View):
    def post(self, request, id):
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.comment_id = id
                form.save()
        return redirect(f'/todo/{id}')



def get_client_ip(request):
    '''получаем ip-адрес клиента'''
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class AddLike(View):
    '''добавление лайков'''
    def get(self, request, id):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip = ip_client, post_id = id)
            return redirect(f'/todo/{id}')
        except:
            new_like = Likes()
            new_like.ip = ip_client
            new_like.post_id = int(id)
            new_like.save()
            return redirect(f'/todo/{id}')


class DelLike(View):
    '''удаление лайков'''
    def get(self, request, id):
        ip_client = get_client_ip(request)
        try:
            Likes.objects.get(ip = ip_client, post_id = id).delete()
            return redirect(f'/todo/{id}')
        except:
            return redirect(f'/todo/{id}')


class TodoUpdateView(UpdateView):
    '''обновление задачи'''
    model = Todo
    template_name = 'create.html'
    form_class = TodoForm


class TodoDeleteView(DeleteView):
    '''удаление задачи'''
    model = Todo
    success_url = '/'
    template_name = 'todo_delete.html'
    context_object_name = 'todo_delete'


def create(request):
    '''добавление задачи'''
    error = ''
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todos')
        else:
            error = 'Неверные данные, поля должны быть заполнены.'

    form = TodoForm()
    context = {
        'form': form,
        'title': 'Добавление задачи',
        'error': error}
    return render(request, 'create.html', context=context)


def about(request):
    return render (request, 'about.html', { 'title': 'О сайте'})


def contact(request):
    return render (request, 'contact.html', { 'title': 'Обратная связь'})


def login(request):
    return render(request, 'login.html', { 'title': 'Войти'})

#_______________________________________________________#

class TodoViewSet(viewsets.ModelViewSet):
    queryset = Todo.objects.all()
    serializer_class = TodoSerializer
    permission_classes = [permissions.AllowAny]
    filter_backends = [filters.OrderingFilter, DjangoFilterBackend, filters.SearchFilter]
    ordering_fields = ['id', 'title', 'description', 'created_date']
    filterset_fields = ['id', 'title', 'description', 'author']
    search_fields = ['title', 'description']
#
#     def get_queryset(self):
#         pk = self.kwargs.get('pk')
#
#         if not pk:
#             return Todo.objects.all()[1:5]
#
#         return Todo.objects.filter(pk = pk)
#
#     @action(methods=['get'], detail=True)
#     def comments(self, request, pk = None):
#         cmts = Comment.objects.get(pk = pk)
#         return Response({'cmts': cmts.comment_text})

# class TodoAPIList(generics.ListCreateAPIView):
#     queryset = Todo.objects.all()
#     serializer_class = TodoSerializer
#     permission_classes = (IsAuthenticatedOrReadOnly,)


# class TodoAPIUpdate(generics.UpdateAPIView):
#     queryset = Todo.objects.all()
#     serializer_class = TodoSerializer
#     permission_classes = (IsAuthenticated, )


# class TodoAPIDetailView(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Todo.objects.all()
#     serializer_class = TodoSerializer

# class TodoAPIDestroy(generics.RetrieveDestroyAPIView):
#     queryset = Todo.objects.all()
#     serializer_class = TodoSerializer
#     permission_classes = (IsAdminReadOnly,)
#

tms/todos/templates/about.html
{% extends 'base_form.html' %}

{% block content %}

    <h1>{{ title }}</h1>
<p>Содержимое страницы о сайте </p>
{% endblock %}

tms/todos/templates/base_form.html
{% load static %}
{% load todos_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'todos/css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.2.1/css/all.css">


</head>
<body>
    <aside>
        <img src="{% static 'todos/images/svitok.jpg' %}" class="image"/>
        <h3>Навигация</h3>

        {% get_menu as menu %}
        <ul>
             {% for m in menu %}
                {% if not forloop.last %}
                    <li><i class="fa-solid fa-house"></i><a href={% url m.url_name %}>{{m.title}}</a>  </li>
                {% else %}
                    <li class = 'last'><i class="fa-solid fa-house"></i><a href={% url m.url_name %}>{{m.title}}</a></li>
                {% endif %}
            {% endfor %}
            <a href="{% url 'create' %}"><li><button class="btn btn-info"><i class="fas fa-plus-circle"></i>Добавить задачу</button></li></a>
        </ul>
    </aside>

    <main>

        {% block mainmenu %}
            <div class="header">
                <ul id="mainmenu" class="mainmenu">
                <li class="logo"><a href="{% url 'todos' %}"><div class="logo"></div></a></li>
                 </ul>
            </div>
        {% endblock mainmenu %}
    </main>
<div>
        {% block content %}
        {% endblock content %}
 </div>
</body>
</html>

tms/todos/templates/contact.html
{% extends 'base_form.html' %}

{% block content %}

    <h1>{{ title }}</h1>
<p>Обратная связь </p>
{% endblock %}

tms/todos/templates/create.html
{% extends 'base_form.html' %}

{% block content %}

    <h1>{{title}}</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.description }}<br>
        {{ form.created_date }}<br>
        {{ form.author }}<br>
        {{ form.completed }}<br>
        <h4><span>{{ error }}</span></h4><br>
        <button class="btn btn-info" type="submit"><i class="fas fa-plus-circle"></i>Добавить задачу </button><br>
    </form>
</div>




{% endblock %}

tms/todos/templates/login.html
{% extends 'base_form.html' %}

{% block content %}

    <h1>{{ title }}</h1>
<p>Авторизация</p>
{% endblock %}

tms/todos/templates/todo.html
{% extends 'base_form.html' %}

{% block title %}Удаление задачи{% endblock %}

{% block content %}

    <h1>{{title}}</h1>

<div class={{todo.block1}}>
<p>{{one_todo.created_date}}</p>
<p>{{one_todo.description}}</p>
    <a href="{% url 'todo_update' one_todo.id %}" class="btn btn-primary btn-sm">Изменить задачу</a>
    <a href="{% url 'todo_delete' one_todo.id %}" class="btn btn-danger btn-sm">Удалить задачу</a>
</div>

<div>
    <br>
    <p>Понравилось: {{ one_todo.likes_set.all.count }}</p>
    <br>
    <a href="{% url 'add_likes' one_todo.id %}" class="btn btn-outline-primary">Нравится </a>
    <a href="{% url 'del_likes' one_todo.id %}" class="btn btn-outline-danger">Не нравится</a>
</div>

<div class="form-comment">
   <div>
       <form action="{% url 'add_comment' one_todo.id %}" method="post">
            {% csrf_token %}
            <div>

                <label><h5>Ваш комментарий:</h5></label>
            <textarea name="comment_text"></textarea>

            </div>

            <div>
                <label><h5>Ваше имя: *</h5></label>
            <input type="text" name="name">
            </div>

            <div>
                <label><h5>Ваш email: *</h5></label>
            <input type="email" name="email_address">
            </div>

            <div>
                <input type="submit">
            </div>

        </form>
    </div>

    <div>

         <label><h5>Комментарии:</h5></label>
        {% for comment in one_todo.comment_set.all %}
        <div class="view-comment">
                <h5>{{ comment.name }}</h5>
                <p class="fw-bold" >
                <h5>{{ comment.comment_text }}</h5>
                </p>
            </div>
        <hr>
        {% endfor %}
    </div>


</div>

<hr>
<div>
    <p>
    <script src="script.js"></script>
    <button id="button" class="button">Complete</button>
    <h6>
        "Кнопка нажималась "
        <span id="counter"></span>
        "раз(а)"
    </h6>
    </p>
</div>
{% endblock %}

tms/todos/templates/todo_delete.html
{% extends 'base_form.html' %}

{% block title %}Удаление задачи{% endblock %}

{% block content %}
<h1>Удаление задачи</h1>
<div class={{todo.block1}}>

    <form method="post">
        {% csrf_token %}
        {{ todo_delete.name }}<br>
        {{ todo_delete.description }}<br>
        {{ todo_delete.created_date}}<br>
        {{ todo_delete.author}}<br>
        <button class="btn btn-danger" type="submit"><i class="fas fa-minus-circle"></i>Удалить задачу </button><br>
    </form>
</div>




{% endblock %}

tms/todos/templates/todos.html
{% extends 'base_form.html' %}

{% block content %}

<h1>{{ title }}</h1>

<h3><a href="https://pomodoro-tracker.com/?lang=ru">Техника Pomodoro</a></h3>
<script src="script.js"></script>

{% for todo in todos %}
<div class={{todo.block1}}>
    <h4>{{todo.author}}</h4>
    <p>{{todo.description}}</p>
    <a href="{% url 'one_todo' todo.id %}" class="btn btn-primary btn-sm">Читать детальнее</a>
</div>
<script></script>
<hr>
{% endfor %}


{% endblock %}